title: A tiny experiment with MathML accessibility
description: This page explores producing MathML from latexml with and without accessibility annotations, and narrating that to English text, for comparison.
