theme: jekyll-theme-minimal
title: MathML accessibility via LaTeXML
description: Experiment with producing MathML from latexml with and without accessibility annotations, with narration to English text.
